# Generated by Django 4.1.7 on 2023-03-18 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('movies', '0008_remove_movie_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='BaseCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='first name')),
                ('last_name', models.CharField(max_length=100, verbose_name='last name')),
                ('age', models.CharField(max_length=100, verbose_name='age')),
                ('is_alive', models.BooleanField(default=True, verbose_name='is_alive')),
                ('image', models.ImageField(default='images/default.png', upload_to='images/', verbose_name='image')),
                ('passed_away_on', models.DateField(blank=True, null=True)),
                ('movie', models.ManyToManyField(related_name='movie_actor', to='movies.movie', verbose_name='movie')),
                ('serial', models.ManyToManyField(related_name='serial_actor', to='movies.movie', verbose_name='serial')),
            ],
        ),
        migrations.CreateModel(
            name='Director',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='director', to='cast_and_crew.basecast', verbose_name='director')),
            ],
        ),
        migrations.CreateModel(
            name='Actor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='cast_and_crew.basecast', verbose_name='director')),
            ],
        ),
    ]
