# Generated by Django 4.1.7 on 2023-03-18 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0004_remove_series_type'),
        ('cast_and_crew', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basecast',
            name='serial',
            field=models.ManyToManyField(related_name='serial_actor', to='series.series', verbose_name='serial'),
        ),
    ]
