# Generated by Django 4.1.7 on 2023-03-18 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cast_and_crew', '0002_alter_basecast_serial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basecast',
            name='movie',
        ),
        migrations.RemoveField(
            model_name='basecast',
            name='serial',
        ),
        migrations.AlterField(
            model_name='actor',
            name='base',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='actor', to='cast_and_crew.basecast', verbose_name='actor'),
        ),
    ]
