# Generated by Django 4.1.7 on 2023-03-18 09:09

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('series', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_number',
            field=models.CharField(default='', max_length=5, verbose_name='episode'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='episode',
            name='serial',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episode', to='series.series', verbose_name='serial'),
        ),
        migrations.CreateModel(
            name='SerialComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('comment', models.TextField(max_length=500, verbose_name='comment')),
                ('rate', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rate')),
                ('is_approve', models.BooleanField(default=False, verbose_name='is_approve')),
                ('is_active', models.BooleanField(default=False, verbose_name='is_active')),
                ('serial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_comment', to='series.series', verbose_name='serial')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serial_comment', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
