# Generated by Django 4.1.7 on 2023-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0002_episode_episode_number_alter_episode_serial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='poster',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='poster'),
        ),
    ]
