# Generated by Django 4.1.7 on 2023-03-27 14:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0006_alter_series_actor_alter_series_director'),
    ]

    operations = [
        migrations.AlterField(
            model_name='series',
            name='imdb_rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='imdb_rate'),
        ),
        migrations.AlterField(
            model_name='series',
            name='rate',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rate'),
        ),
    ]
