# Generated by Django 4.1.7 on 2023-03-27 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('series', '0007_alter_series_imdb_rate_alter_series_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='series',
            name='poster',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='poster'),
        ),
    ]
