# Generated by Django 4.1.7 on 2023-03-12 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='base',
        ),
        migrations.AddField(
            model_name='base',
            name='genre',
            field=models.ManyToManyField(related_name='base', to='movies.genre', verbose_name='genre'),
        ),
    ]
