# Generated by Django 4.1.7 on 2023-03-17 14:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_genre_base_base_genre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Actors',
        ),
        migrations.RemoveField(
            model_name='base',
            name='genre',
        ),
        migrations.DeleteModel(
            name='Director',
        ),
        migrations.DeleteModel(
            name='SavedMovies',
        ),
        migrations.RemoveField(
            model_name='series',
            name='base',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='base',
        ),
        migrations.AddField(
            model_name='movie',
            name='country_made',
            field=models.CharField(default='', max_length=100, verbose_name='country'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='description',
            field=models.TextField(default='', verbose_name='description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(related_name='base', to='movies.genre', verbose_name='genre'),
        ),
        migrations.AddField(
            model_name='movie',
            name='imdb_rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='imdb_rate'),
        ),
        migrations.AddField(
            model_name='movie',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
        migrations.AddField(
            model_name='movie',
            name='rate',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)], verbose_name='rate'),
        ),
        migrations.AddField(
            model_name='movie',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='review'),
        ),
        migrations.AddField(
            model_name='movie',
            name='title',
            field=models.CharField(default='', max_length=100, verbose_name='title'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='type',
            field=models.CharField(default='', max_length=50, verbose_name='type'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2023)], verbose_name='year'),
        ),
        migrations.DeleteModel(
            name='Base',
        ),
        migrations.DeleteModel(
            name='Series',
        ),
    ]
