# Generated by Django 4.1.7 on 2023-03-18 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_alter_moviecomment_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.ImageField(default='images/default.png', upload_to='images/', verbose_name='poster'),
        ),
    ]
